-- Baseline of the schema that Hibernate's ddl-auto created before this project adopted Flyway.
--
-- Dumped from a running instance with pg_dump --schema-only rather than hand-written, so it is a
-- verified match for the JPA entities rather than an approximation of them. From here ddl-auto is
-- off and every change is a numbered migration: the next table added is on the correctness path
-- (embedded_content, V2), and ddl-auto cannot express the index it needs, cannot perform a data
-- migration, and leaves no version history to diff environments against.
--
-- Applied to existing deployments via baseline-on-migrate, which adopts their current schema as
-- version 1 without re-running this file.

CREATE TABLE public.discovered_tables (
    id bigint NOT NULL,
    catalog_name character varying(500),
    discovered_at timestamp(6) without time zone NOT NULL,
    location character varying(1000) NOT NULL,
    metadata_location character varying(1000) NOT NULL,
    partition_spec_json text,
    properties_json text,
    registered boolean NOT NULL,
    registered_at timestamp(6) without time zone,
    schema_json text,
    schema_name character varying(255) NOT NULL,
    sync_job_id character varying(500),
    table_name character varying(255) NOT NULL,
    total_files bigint,
    total_records bigint,
    total_size bigint,
    uuid character varying(255),
    warehouse_url character varying(1000)
);
ALTER TABLE public.discovered_tables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discovered_tables_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.materializations (
    id character varying(255) NOT NULL,
    anchor_sequence_number bigint,
    anchor_snapshot_id bigint,
    catalog_name character varying(255),
    chunk_overlap integer NOT NULL,
    chunk_size integer NOT NULL,
    chunker character varying(255) NOT NULL,
    config_id character varying(32) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    embedding_columns text NOT NULL,
    embedding_version character varying(255) NOT NULL,
    freshness_sla_seconds integer,
    incremental_watermark bigint,
    join_separator character varying(255),
    key_columns text NOT NULL,
    last_error text,
    model_name character varying(255) NOT NULL,
    model_revision character varying(255),
    normalize_vectors boolean NOT NULL,
    priority integer,
    purge_eligible boolean NOT NULL,
    source_table character varying(255) NOT NULL,
    state character varying(32) NOT NULL,
    updated_at timestamp(6) with time zone,
    CONSTRAINT materializations_state_check CHECK (((state)::text = ANY ((ARRAY['REGISTERED'::character varying, 'VALIDATED'::character varying, 'BACKFILLING'::character varying, 'LIVE'::character varying, 'MIGRATING'::character varying, 'PAUSED'::character varying, 'DEGRADED'::character varying, 'RETIRING'::character varying, 'RETIRED'::character varying])::text[])))
);
CREATE TABLE public.sync_jobs (
    job_id character varying(255) NOT NULL,
    catalog_name character varying(255) NOT NULL,
    completed_at timestamp(6) without time zone,
    created_by character varying(255),
    error_details text,
    error_message text,
    register_new_tables boolean NOT NULL,
    s3_path character varying(1000) NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    sync_existing_tables boolean NOT NULL,
    tables_discovered integer,
    tables_failed integer,
    tables_registered integer,
    tables_updated integer,
    CONSTRAINT sync_jobs_status_check CHECK (((status)::text = ANY ((ARRAY['RUNNING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);
CREATE TABLE public.sync_state (
    table_id character varying(255) NOT NULL,
    last_snapshot_id bigint,
    last_sync_at timestamp without time zone
);
CREATE TABLE public.table_configs (
    table_id character varying(255) NOT NULL,
    catalog character varying(255) NOT NULL,
    table_name character varying(255) NOT NULL,
    embedding_columns text NOT NULL,
    model_name character varying(255) NOT NULL,
    embedding_version character varying(255) DEFAULT 'v1'::character varying NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone
);
CREATE TABLE public.work_items (
    id character varying(36) NOT NULL,
    attempts integer NOT NULL,
    committed_at_millis bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    data_file_path character varying(1024) NOT NULL,
    dedup_key character varying(64) NOT NULL,
    kind character varying(16) NOT NULL,
    last_error text,
    lease_expires_at timestamp(6) with time zone,
    lease_owner character varying(128),
    materialization_id character varying(128) NOT NULL,
    max_attempts integer NOT NULL,
    priority integer NOT NULL,
    record_count bigint NOT NULL,
    sequence_number bigint NOT NULL,
    snapshot_id bigint NOT NULL,
    source_table character varying(512) NOT NULL,
    state character varying(16) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT work_items_kind_check CHECK (((kind)::text = ANY ((ARRAY['BACKFILL'::character varying, 'INCREMENTAL'::character varying])::text[]))),
    CONSTRAINT work_items_state_check CHECK (((state)::text = ANY ((ARRAY['PENDING'::character varying, 'LEASED'::character varying, 'DONE'::character varying, 'FAILED'::character varying])::text[])))
);
ALTER TABLE ONLY public.discovered_tables
    ADD CONSTRAINT discovered_tables_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.materializations
    ADD CONSTRAINT materializations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sync_jobs
    ADD CONSTRAINT sync_jobs_pkey PRIMARY KEY (job_id);
ALTER TABLE ONLY public.sync_state
    ADD CONSTRAINT sync_state_pkey PRIMARY KEY (table_id);
ALTER TABLE ONLY public.table_configs
    ADD CONSTRAINT table_configs_catalog_table_name_key UNIQUE (catalog, table_name);
ALTER TABLE ONLY public.table_configs
    ADD CONSTRAINT table_configs_pkey PRIMARY KEY (table_id);
ALTER TABLE ONLY public.materializations
    ADD CONSTRAINT uk_materializations_source_config UNIQUE (source_table, config_id);
ALTER TABLE ONLY public.discovered_tables
    ADD CONSTRAINT ukjeh2fq0nb4pbrutpj70bqfoew UNIQUE (uuid);
ALTER TABLE ONLY public.work_items
    ADD CONSTRAINT uq_work_items_dedup UNIQUE (dedup_key);
ALTER TABLE ONLY public.work_items
    ADD CONSTRAINT work_items_pkey PRIMARY KEY (id);
CREATE INDEX idx_sync_state_last_sync ON public.sync_state USING btree (last_sync_at);
CREATE INDEX idx_table_configs_enabled ON public.table_configs USING btree (enabled);
CREATE INDEX idx_work_items_dispatch ON public.work_items USING btree (state, priority, created_at);
CREATE INDEX idx_work_items_progress ON public.work_items USING btree (materialization_id, state);
CREATE INDEX ix_materializations_source_table ON public.materializations USING btree (source_table);
CREATE INDEX ix_materializations_state ON public.materializations USING btree (state);
ALTER TABLE ONLY public.sync_state
    ADD CONSTRAINT sync_state_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.table_configs(table_id);
